---
- hosts: local
  become: yes
  vars_files:
    - /site/configuration.yml
  pre_tasks:
    - name: Install roles from Ansible Galaxy
      command: ansible-galaxy install {{ item }} --roles-path /ops/roles
      with_items:
        - "{{ ansible_roles_list }}"
    - name: add roles to .gitignore
      lineinfile:
        dest:   '/site/.gitignore'
        regexp: '^\/roles$'
        line:   '/ops/roles/{{ item }}'
        state:  present
      with_items:
        - "{{ ansible_roles_list }}"
  roles:
    - bgrrtt.zim
